import re

class RegexRule(object):
    def __init__(self, regex, name_format):
        self.re = re.compile(regex, re.IGNORECASE)
        self.name_format = name_format

    def apply(self, name):
        match = self.re.match(name)
        if not match:
            return None

        return name_format.format(**match.groupdict())



regex_rules = [
    
]


abbrv_mapping = {
    "xtra": "extra",
    "lrg": "large",
    "prem": "premium",
    "stk": "steak",
    "chz": "cheese",
    "prod": "product",
    "pc": "piece",
    "pltr": "platter",
    "btr": "batter",
    "btrd": "battered",
    "ult": "ultimate",
    "knr": "Knorr",
    "frt": "fruit",
    "tndr": "tender",
    "fr": "fried",
    "chx": "chicken",
    "brd": "bread",
    "rt": "root",
    "ct": "count",
    "charbroilr": "charbroiler",
    "alum": "aluminum",
    "lg": "large",
    "sml": "small",
    "clr": "clear",
    "hng": "hinged",
    "sftsrv": "softserve",
    "cke": "cake",
    "gldn": "golden",
    "crm": "cream",
    "muf": "muffin",
    "muff": "muffin",
    "dinr": "dinner",
    "dnr": "dinner",
    "rnd": "round",
    "mesquie": "mesquite",
    "dzn": "dozen",
    "hndl": "handle",
    "mozz": "mozzarella",
    "hvy": "heavy",
    "chem": "chemical",
    "corp": "corporation",
    "ntrl": "natural",
    "bisc": "biscuits",
    "ketc": "ketchup",
    "upsdwn": "upside down",
    "bev": "beverage",
    "clsc": "classic",
    "vrty": "variety",
    "drk": "dark",
    "hdl": "handle",
    "sft": "soft",
    "assem": "assembly",
    "mnt": "mount",
    "qrt": "quart",
    "crakers": "crackers",
    "ter": "teriyaki",
    "sa": "sauce",
    "pstl": "pastel",
    "choc": "chocolate",
    "ast": "assorted",
    "nab": "Nabisco",
    "chp": "chip",
    "cooki": "cookie",
    "ckie": "cookie",
    "crkr": "cracker",
    "oatml": "oatmeal",
    "rainbw": "rainbow",
    "cntry": "country",
    "chky": "chunky",
    "gld": "gold",
    "ital": "italian",
    "lt": "lite",
    "smk": "Smucker's",
    "thou": "thousand",
    "blk": "black",
    "fm": "foam",
    "aspgus": "asparagus",
    "cabb": "cabbage",
    "chipotel": "chipotle",
    "mushrm": "mushroom",
    "jalape": "jalepeno",
    "gls": "glass",
    "r. bristol": "Royal Bristol",
    "r.bristol": "Royal Bristol",
    "dess": "dessert",
    "knf": "knife",
    "spn": "spoon",
    "tiss": "tissue",
    "astd": "assorted",
    "sauc": "sauce",
    "frnk": "frank",
    "swt": "sweet",
    
}

filter_rules = [
    "no longer on file",
    "hamburger",
    "gum",
    "seafood",
    "shot glass",
    "shrimp",
    "salmon",
    "crab",
    "octopus",
    "whole chicken",
    "pit ham",
    "always fresh beef",
    "always fresh chicken",
    "always fresh pork",
    "ground chuck",
    "pancake mix",
    "mutton",
    "bacon",
    "bake n joy  mix",  # regex? Because the double space...
    "muffin batter",
    "muffin mix",
    "cookie batter",
    "mix cookie",
    "chicken fingers",
    "chicken tenders",
    "pasta",
    "spaghetti",
    "barstool",
    "baseball cap",
    "bean",
    "cow feet",
    "liver",
    "cheek meat",
    "baking stone",
    "italian sausage",
    "fries",
    "raw",
    "mozzarella sticks",
    "jalapeno poppers",
    "battered",
    "breaded",
    "grilled",
    "sweet potato platter fry",
    "oven ready",
    "chicken wing",
    "onion rings",
    "cleaner oven & grill",
    "black steer",
    "shoes",
    "box pizza",
    "floss",
    "flour",
    "panini",
    "bulb",
    "pan",
    "butane",
    "wine",
    "china",
    "candle",
    "worktable",
    "fry king oil",
    "caviar",
    "champagne",
    "dough",
    "charbroiler",
    "meat tenderizer",
    "clam",
    "mashed potatoes granules",
    "matzoh meal",
    "mashed potatoes complete",
    "tuna",
    "corn",
    "noodles",
    "noodle",
    "linguini",
    "counterfeit",
    "coupon",
    "orzo",
    "penne",
    "rotini",
    "fusilli",
    "dececco",
    "thermometer",
    "xlerator",
    "oven",
    "gravy mix",
    "refrigerator",
    "fridge",
    "freezer",
    "faucet",
    "insect killer",
    "swatter",
    "fruit fly",
    "batter",
    "scaler",
    "cushion",
    "chair",
    "shellfish",
    "fryer",
    "scale",
    "biscuit mix",
    "cake mix",
    "grease trap",
    "outdoor grill",
    "hand dryer",
    "spout",
    "gas",
    "heat & serve",
    "microwave",
    "rice pilaf",
    "mouse trap",
    "pizza box",
    "pizza screen",
    "pizza peel",
    "cavatappi",
    "ziti",
    "farfalle",
    "orecchiette",
    "parpadele",
    "griddle",
    "chafer",
    "raid",
    "range",
    "breader",
    "fish",
    "cous cous",
    "beard protector",
    "safe",
    
]

category_filter_rules = [
    "Seafood",
    "Deli Meats & Sausage",
    "Fresh & Frozen Meats",
    "Frozen Foods"
]