name_filters = [
    "no longer on file",
    "hamburger",
    "gum",
    "seafood",
    "shot glass",
    "shrimp",
    "salmon",
    "crab",
    "octopus",
    "whole chicken",
    "pit ham",
    "always fresh beef",
    "always fresh chicken",
    "always fresh pork",
    "ground chuck",
    "pancake mix",
    "mutton",
    "bacon",
    "bake n joy  mix",  # regex? Because the double space...
    "muffin batter",
    "muffin mix",
    "cookie batter",
    "mix cookie",
    "chicken fingers",
    "chicken tenders",
    "pasta",
    "spaghetti",
    "barstool",
    "baseball cap",
    "bean",
    "cow feet",
    "liver",
    "cheek meat",
    "baking stone",
    "italian sausage",
    "fries",
    "raw",
    "mozzarella sticks",
    "jalapeno poppers",
    "battered",
    "breaded",
    "grilled",
    "sweet potato platter fry",
    "oven ready",
    "chicken wing",
    "onion rings",
    "cleaner oven & grill",
    "black steer",
    "shoes",
    "box pizza",
    "floss",
    "flour",
    "panini",
    "bulb",
    "pan",
    "butane",
    "wine",
    "china",
    "candle",
    "worktable",
    "fry king oil",
    "caviar",
    "champagne",
    "dough",
    "charbroiler",
    "meat tenderizer",
    "clam",
    "mashed potatoes granules",
    "matzoh meal",
    "mashed potatoes complete",
    "tuna",
    "corn",
    "noodles",
    "noodle",
    "linguini",
    "counterfeit",
    "coupon",
    "orzo",
    "penne",
    "rotini",
    "fusilli",
    "dececco",
    "thermometer",
    "xlerator",
    "oven",
    "gravy mix",
    "refrigerator",
    "fridge",
    "freezer",
    "faucet",
    "insect killer",
    "swatter",
    "fruit fly",
    "batter",
    "scaler",
    "cushion",
    "chair",
    "shellfish",
    "fryer",
    "scale",
    "biscuit mix",
    "cake mix",
    "grease trap",
    "outdoor grill",
    "hand dryer",
    "spout",
    "gas",
    "heat & serve",
    "microwave",
    "rice pilaf",
    "mouse trap",
    "pizza box",
    "pizza screen",
    "pizza peel",
    "cavatappi",
    "ziti",
    "farfalle",
    "orecchiette",
    "parpadele",
    "griddle",
    "chafer",
    "raid",
    "range",
    "breader",
    "fish",
    "cous cous",
    "beard protector",
    "safe",
    "yeast",
    "urinal",
    "snow cone",
    "lobster bisque",
    "stove top",
    "stovetop",
    "escargo",
    "tide",
    "toaster",
    "cast iron",
    "shirt",
    "apron",
    "blue gel",
    "1 gallon storage      sunset",
    "liquid light",
    
]

category_filters = [
    "seafood",
    "deli seats & sausage",
    "fresh & frozen meats",
    "frozen foods"
]

def include_category(category_name):
    return category_name.lower() not in category_filters

def include_product(product_name):
    product_name = product_name.lower()
    for filter_term in name_filters:
        if filter_term in product_name:
            return False
    return True